# generated by datamodel-codegen:
#   filename:  ftir.embed.schema.json
#   timestamp: 2024-11-27T07:38:33+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class BeamsplitterType(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class MichelsonInterferometerAcquisitionModeSetting(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class ReferenceIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class EquipmentSerialNumber(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class AssayComment(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class AssayDataIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class SamplePreparationDescription(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class ExperimentalDataIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class SampleMeasurementInterfaceType(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class AnalyticalMethodIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class MeasurementIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class MeasurementTime(BaseModel):
    value: datetime
    field_type: str = Field(..., alias="@type")


class SampleIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class FieldComponentDatatype(Enum):
    double = "double"
    float = "float"
    decimal = "decimal"
    integer = "integer"
    byte = "byte"
    int = "int"
    short = "short"
    long = "long"
    string = "string"
    boolean = "boolean"
    dateTime = "dateTime"


class Scale(Enum):
    nominal = "nominal"
    ordinal = "ordinal"
    cardinal = "cardinal"
    interval = "interval"
    range = "range"


class Dimension(BaseModel):
    field_componentDatatype: FieldComponentDatatype = Field(
        ...,
        alias="@componentDatatype",
        description="Subset of XSD datatypes supported in simple models",
    )
    concept: str = Field(
        ...,
        description="A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.",
    )
    unit: Optional[str] = Field(
        None,
        description="A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.",
    )
    scale: Optional[Scale] = None
    field_asm_fill_value: Optional[Union[str, float, int, bool]] = Field(
        None, alias="$asm.fill-value"
    )


class Measure(BaseModel):
    field_componentDatatype: FieldComponentDatatype = Field(
        ...,
        alias="@componentDatatype",
        description="Subset of XSD datatypes supported in simple models",
    )
    concept: str = Field(
        ...,
        description="A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.",
    )
    unit: Optional[str] = Field(
        None,
        description="A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.",
    )
    scale: Optional[Scale] = None
    field_asm_fill_value: Optional[Union[str, float, int, bool]] = Field(
        None, alias="$asm.fill-value"
    )


class CubeStructure(BaseModel):
    dimensions: List[Dimension] = Field(..., max_items=1, min_items=1)
    measures: List[Measure] = Field(..., max_items=1, min_items=1)


class Type(Enum):
    linear = "linear"
    logarithmic = "logarithmic"


class Dimensions(BaseModel):
    type: Optional[Type] = "linear"
    start: Optional[float] = 1
    length: Optional[float] = None
    incr: Optional[float] = 1


class Data1(BaseModel):
    measures: List[
        Union[List[Optional[float]], List[Optional[bool]], List[Optional[str]]]
    ]


class Data2(BaseModel):
    points: List[List[Optional[Union[float, bool, str]]]]


class Data3(BaseModel):
    dimensions: List[Union[Union[List[float], List[bool], List[str]], Dimensions]]


class Data4(Data1, Data3):
    pass


class Data5(Data2, Data3):
    pass


class Data(BaseModel):
    __root__: Union[Data4, Data5]


class InfraredInterferogramDataCube(BaseModel):
    label: Optional[str] = None
    cube_structure: Optional[CubeStructure] = Field(None, alias="cube-structure")
    data: Optional[Data] = None


class OpticalVelocitySetting(BaseModel):
    value: float
    unit: str = Field(
        "cm/s",
        const=True,
        description="A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.",
    )
    field_type: Optional[str] = Field(
        None,
        alias="@type",
        description="A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.",
    )


class DetectorGainSetting(BaseModel):
    value: float
    unit: str = Field(
        "(unitless)",
        const=True,
        description="A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.",
    )
    field_type: Optional[str] = Field(
        None,
        alias="@type",
        description="A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.",
    )


class Resolution(BaseModel):
    value: float
    unit: str = Field(
        "1/cm",
        const=True,
        description="A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.",
    )
    field_type: Optional[str] = Field(
        None,
        alias="@type",
        description="A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.",
    )


class ApertureSizeSetting(BaseModel):
    value: float
    unit: str = Field(
        "nm",
        const=True,
        description="A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.",
    )
    field_type: Optional[str] = Field(
        None,
        alias="@type",
        description="A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.",
    )


class NumberOfAverages(BaseModel):
    value: float
    unit: str = Field(
        "(unitless)",
        const=True,
        description="A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.",
    )
    field_type: Optional[str] = Field(
        None,
        alias="@type",
        description="A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.",
    )


class BackgroundDocument(BaseModel):
    infrared_interferogram_data_cube: InfraredInterferogramDataCube = Field(
        ..., alias="infrared interferogram data cube"
    )
    optical_velocity_setting: OpticalVelocitySetting = Field(
        ..., alias="optical velocity setting"
    )
    detector_gain_setting: DetectorGainSetting = Field(
        ..., alias="detector gain setting"
    )
    resolution: Resolution
    aperture_size_setting: ApertureSizeSetting = Field(
        ..., alias="aperture size setting"
    )
    number_of_averages: NumberOfAverages = Field(..., alias="number of averages")


class TransmittanceSpectrumDataCube(BaseModel):
    label: Optional[str] = None
    cube_structure: Optional[CubeStructure] = Field(None, alias="cube-structure")
    data: Optional[Data] = None


class ReflectanceSpectrumDataCube(BaseModel):
    label: Optional[str] = None
    cube_structure: Optional[CubeStructure] = Field(None, alias="cube-structure")
    data: Optional[Data] = None


class AbsorptionSpectrumDataCube(BaseModel):
    label: Optional[str] = None
    cube_structure: Optional[CubeStructure] = Field(None, alias="cube-structure")
    data: Optional[Data] = None


class MeasurementDocument(BaseModel):
    optical_velocity_setting: OpticalVelocitySetting = Field(
        ..., alias="optical velocity setting"
    )
    transmittance_spectrum_data_cube: TransmittanceSpectrumDataCube = Field(
        ..., alias="transmittance spectrum data cube"
    )
    resolution: Resolution
    number_of_averages: NumberOfAverages = Field(..., alias="number of averages")
    infrared_interferogram_data_cube: InfraredInterferogramDataCube = Field(
        ..., alias="infrared interferogram data cube"
    )
    reflectance_spectrum_data_cube: ReflectanceSpectrumDataCube = Field(
        ..., alias="reflectance spectrum data cube"
    )
    detector_gain_setting: DetectorGainSetting = Field(
        ..., alias="detector gain setting"
    )
    absorption_spectrum_data_cube: AbsorptionSpectrumDataCube = Field(
        ..., alias="absorption spectrum data cube"
    )
    aperture_size_setting: ApertureSizeSetting = Field(
        ..., alias="aperture size setting"
    )


class FourierTransformInfraredDocument(BaseModel):
    background_document: Optional[BackgroundDocument] = Field(
        None, alias="background document"
    )
    measurement_document: Optional[MeasurementDocument] = Field(
        None, alias="measurement document"
    )


class ConformanceAssessment(BaseModel):
    value: bool
    field_type: str = Field(..., alias="@type")


class MaterialIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class DetectorType(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class BatchIdentifier(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class Analyst(BaseModel):
    value: str
    field_type: str = Field(..., alias="@type")


class Model(BaseModel):
    beamsplitter_type: Union[str, BeamsplitterType] = Field(
        ..., alias="beamsplitter type"
    )
    michelson_interferometer_acquisition_mode_setting: Optional[
        Union[str, MichelsonInterferometerAcquisitionModeSetting]
    ] = Field(None, alias="michelson interferometer acquisition mode setting")
    reference_identifier: Optional[Union[str, ReferenceIdentifier]] = Field(
        None, alias="reference identifier"
    )
    equipment_serial_number: Union[str, EquipmentSerialNumber] = Field(
        ..., alias="equipment serial number"
    )
    assay_comment: Optional[Union[str, AssayComment]] = Field(
        None, alias="assay comment"
    )
    assay_data_identifier: Optional[Union[str, AssayDataIdentifier]] = Field(
        None, alias="assay data identifier"
    )
    sample_preparation_description: Optional[
        Union[str, SamplePreparationDescription]
    ] = Field(None, alias="sample preparation description")
    experimental_data_identifier: Optional[Union[str, ExperimentalDataIdentifier]] = (
        Field(None, alias="experimental data identifier")
    )
    sample_measurement_interface_type: Optional[
        Union[str, SampleMeasurementInterfaceType]
    ] = Field(None, alias="sample measurement interface type")
    analytical_method_identifier: Optional[Union[str, AnalyticalMethodIdentifier]] = (
        Field(None, alias="analytical method identifier")
    )
    measurement_identifier: Union[str, MeasurementIdentifier] = Field(
        ..., alias="measurement identifier"
    )
    measurement_time: Union[datetime, MeasurementTime] = Field(
        ..., alias="measurement time"
    )
    sample_identifier: Union[str, SampleIdentifier] = Field(
        ..., alias="sample identifier"
    )
    Fourier_transform_infrared_document: Optional[FourierTransformInfraredDocument] = (
        Field(None, alias="Fourier transform infrared document")
    )
    conformance_assessment: Optional[Union[bool, ConformanceAssessment]] = Field(
        None, alias="conformance assessment"
    )
    material_identifier: Optional[Union[str, MaterialIdentifier]] = Field(
        None, alias="material identifier"
    )
    detector_type: Union[str, DetectorType] = Field(..., alias="detector type")
    batch_identifier: Optional[Union[str, BatchIdentifier]] = Field(
        None, alias="batch identifier"
    )
    analyst: Union[str, Analyst]
