# generated by datamodel-codegen:
#   filename:  raman.embed.schema.json
#   timestamp: 2024-11-28T09:19:58+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ApodizationRaman(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class MethodName(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class AnalyteName(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class HitQualityIndexThreshold(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['%'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class IntegrationTime(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['ms'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class FieldComponentDatatype(Enum):
    double = 'double'
    float = 'float'
    decimal = 'decimal'
    integer = 'integer'
    byte = 'byte'
    int = 'int'
    short = 'short'
    long = 'long'
    string = 'string'
    boolean = 'boolean'
    dateTime = 'dateTime'


class Scale(Enum):
    nominal = 'nominal'
    ordinal = 'ordinal'
    cardinal = 'cardinal'
    interval = 'interval'
    range = 'range'


class Dimension(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_componentDatatype: FieldComponentDatatype = Field(
        ...,
        alias='@componentDatatype',
        description='Subset of XSD datatypes supported in simple models',
    )
    concept: str = Field(
        ...,
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )
    unit: Optional[str] = Field(
        None,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    scale: Optional[Scale] = None
    field_asm_fill_value: Optional[Union[str, float, int, bool]] = Field(
        None, alias='$asm.fill-value'
    )


class Measure(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_componentDatatype: FieldComponentDatatype = Field(
        ...,
        alias='@componentDatatype',
        description='Subset of XSD datatypes supported in simple models',
    )
    concept: str = Field(
        ...,
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )
    unit: Optional[str] = Field(
        None,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    scale: Optional[Scale] = None
    field_asm_fill_value: Optional[Union[str, float, int, bool]] = Field(
        None, alias='$asm.fill-value'
    )


class CubeStructure(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    dimensions: List[Dimension] = Field(..., max_length=1, min_length=1)
    measures: List[Measure] = Field(..., max_length=1, min_length=1)


class Type(Enum):
    linear = 'linear'
    logarithmic = 'logarithmic'


class Dimensions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[Type] = 'linear'
    start: Optional[float] = 1
    length: Optional[float] = None
    incr: Optional[float] = 1


class Data1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    measures: List[
        Union[List[Optional[float]], List[Optional[bool]], List[Optional[str]]]
    ]


class Data2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    points: List[List[Optional[Union[float, bool, str]]]]


class Data3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    dimensions: List[Union[Union[List[float], List[bool], List[str]], Dimensions]]


class Data4(Data1, Data3):
    pass
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Data5(Data2, Data3):
    pass
    model_config = ConfigDict(
        populate_by_name=True,
    )


class Data(RootModel[Union[Data4, Data5]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Union[Data4, Data5]


class RamanSpectrumDataCube(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    label: Optional[str] = None
    cube_structure: Optional[CubeStructure] = Field(None, alias='cube-structure')
    data: Optional[Data] = None


class HitQualityIndexMargin(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['%'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class Analyst(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class EquipmentSerialNumber(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class TopIdentifiedSubstance(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class Resolution(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['1/cm'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class AnalyteHitQualityIndex(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['%'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class ExcitationLaserPowerSetting(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['mW'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class BatchIdentifier(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class AcquisitionTime(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: datetime
    field_type: str = Field(..., alias='@type')


class ExcitationLaserWavelengthSettingRaman(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['nm'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class DarkBackgroundCorrectionActive(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: bool
    field_type: str = Field(..., alias='@type')


class ZeroFillingFactorRaman(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['(unitless)'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class SampleIdentifier(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class LibrarySearchStopWavenumber(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['1/cm'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class NumberOfAverages(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['(unitless)'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class MeasurementIdentifier(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class SpectrumLibraryName(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class PhaseCorrectionRaman(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: str
    field_type: str = Field(..., alias='@type')


class LibrarySearchStartWavenumber(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    unit: Literal['1/cm'] = Field(
        ...,
        description='A unit is referenced by its QUDT symbol. It MUST be unique within the QUDT units defined in the vocabularies declared in the manifest.',
    )
    field_type: Optional[str] = Field(
        None,
        alias='@type',
        description='A class reference is the SKOS preferred label of a class. This label MUST be unique within the transitive closure of the vocabulary referenced by the manifest.',
    )


class MeasurementTime(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: datetime
    field_type: str = Field(..., alias='@type')


class Model(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    apodization__Raman_: Optional[Union[str, ApodizationRaman]] = Field(
        None, alias='apodization (Raman)'
    )
    method_name: Optional[Union[str, MethodName]] = Field(None, alias='method name')
    analyte_name: Optional[Union[str, AnalyteName]] = Field(None, alias='analyte name')
    hit_quality_index_threshold: Optional[HitQualityIndexThreshold] = Field(
        None, alias='hit quality index threshold'
    )
    integration_time: IntegrationTime = Field(..., alias='integration time')
    Raman_spectrum_data_cube: RamanSpectrumDataCube = Field(
        ..., alias='Raman spectrum data cube'
    )
    hit_quality_index_margin: Optional[HitQualityIndexMargin] = Field(
        None, alias='hit quality index margin'
    )
    analyst: Optional[Union[str, Analyst]] = None
    equipment_serial_number: Optional[Union[str, EquipmentSerialNumber]] = Field(
        None, alias='equipment serial number'
    )
    top_identified_substance: Optional[Union[str, TopIdentifiedSubstance]] = Field(
        None, alias='top identified substance'
    )
    resolution: Optional[Resolution] = None
    analyte_hit_quality_index: Optional[AnalyteHitQualityIndex] = Field(
        None, alias='analyte hit quality index'
    )
    excitation_laser_power_setting: ExcitationLaserPowerSetting = Field(
        ..., alias='excitation laser power setting'
    )
    batch_identifier: Optional[Union[str, BatchIdentifier]] = Field(
        None, alias='batch identifier'
    )
    acquisition_time: Optional[Union[datetime, AcquisitionTime]] = Field(
        None, alias='acquisition time'
    )
    excitation_laser_wavelength_setting__Raman_: (
        ExcitationLaserWavelengthSettingRaman
    ) = Field(..., alias='excitation laser wavelength setting (Raman)')
    dark_background_correction_active: Optional[
        Union[bool, DarkBackgroundCorrectionActive]
    ] = Field(None, alias='dark background correction active')
    zero_filling_factor__Raman_: Optional[ZeroFillingFactorRaman] = Field(
        None, alias='zero filling factor (Raman)'
    )
    sample_identifier: Union[str, SampleIdentifier] = Field(
        ..., alias='sample identifier'
    )
    library_search_stop_wavenumber: Optional[LibrarySearchStopWavenumber] = Field(
        None, alias='library search stop wavenumber'
    )
    number_of_averages: NumberOfAverages = Field(..., alias='number of averages')
    measurement_identifier: Union[str, MeasurementIdentifier] = Field(
        ..., alias='measurement identifier'
    )
    spectrum_library_name: Optional[Union[str, SpectrumLibraryName]] = Field(
        None, alias='spectrum library name'
    )
    phase_correction__Raman_: Optional[Union[str, PhaseCorrectionRaman]] = Field(
        None, alias='phase correction (Raman)'
    )
    library_search_start_wavenumber: Optional[LibrarySearchStartWavenumber] = Field(
        None, alias='library search start wavenumber'
    )
    measurement_time: Union[datetime, MeasurementTime] = Field(
        ..., alias='measurement time'
    )
