line-length = 79
target-version = "py310"
exclude = [
    "fairvibspec/core/fairvibspec.py",
]

[lint]
select = ["E", "F", "I", "B", "UP", "SIM"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["fairvibspec"]
